version: '{branch} - {build}'

branches:
  only:
    - master
    - develop


environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8

install:
  - go version
  - go env
  - go get -v github.com/deckarep/golang-set
  - go get -v github.com/nhoya/goPwned
  - go get -v github.com/jessevdk/go-flags
  - go get -v gopkg.in/src-d/go-git.v4
  - go get -v github.com/jaytaylor/html2text
  - go get -v gopkg.in/ns3777k/go-shodan.v2/shodan

build_script:
  - go build

artifacts:
  - path: gosint.exe
